apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: flaresolverr
  name: flaresolverr
spec:
  ports:
    - name: "8191"
      port: 8191
      targetPort: 8191
  selector:
    io.kompose.service: flaresolverr
status:
  loadBalancer: {}
