apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: booklore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: lscr.io/linuxserver/mariadb:11.4.5
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: booklore
        - name: MYSQL_USER
          value: booklore
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /config
        livenessProbe:
          exec:
            command: ["mariadb-admin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mariadb-admin", "ping", "-h", "localhost"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  namespace: booklore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booklore
  template:
    metadata:
      labels:
        app: booklore
    spec:
      containers:
      - name: booklore
        image: ghcr.io/adityachandelgit/booklore-app:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        - name: DATABASE_URL
          value: jdbc:mariadb://mariadb.booklore.svc.cluster.local:3306/booklore
        - name: DATABASE_USERNAME
          value: booklore
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password
        - name: SWAGGER_ENABLED
          value: "false"
        ports:
        - containerPort: 6060
        volumeMounts:
        - name: booklore-data
          mountPath: /app/data
        - name: booklore-books
          mountPath: /books
      volumes:
      - name: booklore-data
        persistentVolumeClaim:
          claimName: booklore-data-pvc
      - name: booklore-books
        persistentVolumeClaim:
          claimName: booklore-books-pvc