apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.28.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/wuhu/prod/prometheus/values.yaml
    - repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
