apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: navidrome-claim1
  name: navidrome-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
