apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
spec:
  selector:
    app: excalidraw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: excalidraw.haijin666.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excalidraw-service
                port:
                  number: 80
