apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mytb
  name: mytb
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 9090
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "7070"
      port: 7070
      targetPort: 7070
    - name: "5683"
      port: 5683
      protocol: UDP
      targetPort: 5683
    - name: "5684"
      port: 5684
      protocol: UDP
      targetPort: 5684
    - name: "5685"
      port: 5685
      protocol: UDP
      targetPort: 5685
    - name: "5686"
      port: 5686
      protocol: UDP
      targetPort: 5686
    - name: "5687"
      port: 5687
      protocol: UDP
      targetPort: 5687
    - name: "5688"
      port: 5688
      protocol: UDP
      targetPort: 5688
  selector:
    io.kompose.service: mytb
status:
  loadBalancer: {}
