apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: guacd
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/next-terminal-default: "true"
        io.kompose.service: guacd
    spec:
      containers:
        - image: dushixiang/guacd:latest
          name: guacd
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/next-terminal/data
              name: guacd-claim0
      restartPolicy: Always
      volumes:
        - name: guacd-claim0
          persistentVolumeClaim:
            claimName: guacd-claim0
status: {}
