apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: next-terminal
  name: next-terminal
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8088
  selector:
    io.kompose.service: next-terminal
status:
  loadBalancer: {}
