apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: next-terminal
  name: next-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: next-terminal
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/next-terminal-default: "true"
        io.kompose.service: next-terminal
    spec:
      containers:
        - env:
            - name: DB
              value: sqlite
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
          image: dushixiang/next-terminal:latest
          name: next-terminal
          ports:
            - containerPort: 8088
              hostPort: 8088
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: next-terminal-claim0
            - mountPath: /usr/local/next-terminal/data
              name: next-terminal-claim1
      restartPolicy: Always
      volumes:
        - name: next-terminal-claim0
          persistentVolumeClaim:
            claimName: next-terminal-claim0
        - name: next-terminal-claim1
          persistentVolumeClaim:
            claimName: next-terminal-claim1
status: {}
