apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: recorder
  name: recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recorder
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/bililive-default: "true"
        io.kompose.service: recorder
    spec:
      containers:
        - image: bililive/recorder:latest
          name: recorder
          ports:
            - containerPort: 2356
              hostPort: 2356
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /rec
              name: recorder-claim0
      restartPolicy: Always
      volumes:
        - name: recorder-claim0
          persistentVolumeClaim:
            claimName: recorder-claim0
status: {}
