---
- hosts: master_bootstrap
  roles:
  - role: master_bootstrap

- hosts: worker_bootstrap
  roles:
  - role: worker_bootstrap

- hosts: master
  roles:
  - role: master

- hosts: worker
  roles:
  - role: worker