apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: chrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: chrome
        image: ich777/chrome
        ports:
        - containerPort: 8080
        env:
        - name: CUSTOM_RES_W
          value: "1280"
        - name: CUSTOM_RES_H
          value: "768"
        - name: UID
          value: "99"
        - name: GID
          value: "100"
        - name: UMASK
          value: "000"
        - name: DATA_PERM
          value: "770"
        volumeMounts:
        - name: chrome-data
          mountPath: /chrome
      volumes:
      - name: chrome-data
        persistentVolumeClaim:
          claimName: chrome-data
