apiVersion: v1
kind: Namespace
metadata:
  name: "chrome"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium
  namespace: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium
  template:
    metadata:
      labels:
        app: chromium
    spec:
      containers:
        - name: chromium
          image: lscr.io/linuxserver/chromium:latest
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Shanghai"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chromium-secret
                  key: PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
          securityContext:
            seccompProfile:
              type: Unconfined
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: chromium-pvc
      securityContext:
        seccompProfile:
          type: Unconfined
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"