apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chromium-ingress
  namespace: chrome
spec:
  rules:
    - host: chrome.haijin666.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chromium-service
                port:
                  number: 3000