apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromium-pvc
  namespace: chrome
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi