apiVersion: v1
kind: Service
metadata:
  name: chromium-service
  namespace: chrome
spec:
  selector:
    app: chromium
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP