apiVersion: v1
kind: Service
metadata:
  name: docmost
  namespace: docmost
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: docmost
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: docmost
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: docmost
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
