apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless-chrome
  labels:
    app: browserless-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless-chrome
  template:
    metadata:
      labels:
        app: browserless-chrome
    spec:
      containers:
      - name: browserless-chrome
        image: browserless/chrome
        ports:
        - containerPort: 3000
