apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanagergotifybridge
  name: alertmanagergotifybridge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanagergotifybridge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/alertmanagergotifybridge-default: "true"
        io.kompose.service: alertmanagergotifybridge
    spec:
      containers:
        - env:
            - name: GOTIFY_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: gotify-secrets
                  key: GOTIFY_ENDPOINT
            - name: GOTIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gotify-secrets
                  key: GOTIFY_TOKEN
          image: ghcr.io/druggeri/alertmanager_gotify_bridge:master
          name: alertmanagergotifybridge
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /templates
              name: alertmanagergotifybridge-claim0
      restartPolicy: Always
      volumes:
        - name: alertmanagergotifybridge-claim0
          persistentVolumeClaim:
            claimName: alertmanagergotifybridge-claim0
status: {}
