apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared-daemonset
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: token
        volumeMounts:
        - name: cloudflared-cred
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: cloudflared-cred
        secret:
          secretName: cloudflared-secret
