apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/chjtxwd/homelab-k3s-gitops'
    path: wuhu-x86/argo-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
