apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qinglong-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qinglong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qinglong
  template:
    metadata:
      labels:
        app: qinglong
    spec:
      containers:
      - name: qinglong
        image: whyour/qinglong:latest
        ports:
        - containerPort: 5700
        volumeMounts:
        - name: qinglong-data
          mountPath: /ql/data
      volumes:
      - name: qinglong-data
        persistentVolumeClaim:
          claimName: qinglong-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: qinglong-service
spec:
  selector:
    app: qinglong
  ports:
  - port: 80
    targetPort: 5700
  type: ClusterIP