apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  config.yml: |
    rpc:
      enable: true
      bind: :8080
    debug: false
    interval: 20
    out_put_path: /srv/bililive
    ffmpeg_path: ""
    log:
      out_put_folder: ./
      save_last_log: true
      save_every_log: false
    feature:
      use_native_flv_parser: false
      remove_symbol_other_character: false
    live_rooms:
    - url: https://live.douyin.com/95931337431
      is_listening: true
      quality: 3
    - url: https://live.douyin.com/41064345870
      is_listening: true
      quality: 3
    - url: https://live.douyin.com/zzai030
      is_listening: true
      quality: 3 
    - url: https://live.douyin.com/65001189985
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/26095888
      is_listening: true
      audio_only: true
      quality: 3   
    - url: https://live.bilibili.com/21704593
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/21903176
      is_listening: true
      quality: 3   
    - url: https://live.bilibili.com/22580654
      is_listening: true
      quality: 3  
    - url: https://live.bilibili.com/4195167
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/31215292
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/1319379
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/24791581
      is_listening: true
      quality: 3 
    - url: https://live.douyin.com/87490980833
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/10535760
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/279
      is_listening: true
      quality: 3 
    - url: https://live.bilibili.com/689
      is_listening: true
      quality: 3 
    out_put_tmpl: ""
    video_split_strategies:
      on_room_name_changed: false
      max_duration: 0s
    cookies: {}
    on_record_finished:
      convert_to_mp4: true
      delete_flv_after_convert: true
      custom_commandline: ""
    timeout_in_us: 60000000
