apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  config.yml: |
    rpc:
      enable: true
      bind: :8080
    debug: false
    interval: 20
    out_put_path: /srv/bililive
    ffmpeg_path: ""
    log:
      out_put_folder: ./
      save_last_log: true
      save_every_log: false
    feature:
      use_native_flv_parser: false
      remove_symbol_other_character: false
    live_rooms:
    - url: https://www.douyu.com/9642214?dyshid=0-693fcb44c740f3c7f08e654900041601&dyshci=174
      is_listening: true
      quality: 0
    - url: https://live.douyin.com/95931337431
      is_listening: true
      quality: 0
    - url: https://www.douyu.com/20360?dyshid=0-693fcb44c740f3c7f08e654900041601&dyshci=1282
      is_listening: true
      quality: 0
    - url: https://live.douyin.com/41064345870
      is_listening: true
      quality: 0
    - url: https://live.douyin.com/171250979
      is_listening: true
      quality: 0
    - url: https://live.douyin.com/kaoyan.666
      is_listening: true
      quality: 0
    out_put_tmpl: ""
    video_split_strategies:
      on_room_name_changed: false
      max_duration: 30m0s
      max_file_size: 0
    cookies: {}
    on_record_finished:
      convert_to_mp4: true
      delete_flv_after_convert: true
      custom_commandline: ""
    timeout_in_us: 60000000
