apiVersion: apps/v1
kind: Deployment
metadata:
  name: bililive-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bililive-go
  template:
    metadata:
      labels:
        app: bililive-go
    spec:
      containers:
      - name: bililive-go
        image: chigusa/bililive-go
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE
          value: /etc/bililive-go/config.yml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/bililive-go # 挂载整个 ConfigMap
      volumes:
      - name: config-volume
        configMap:
          name: config-map # 指向上面创建的ConfigMap的名称
