apiVersion: v1
kind: Service
metadata:
  name: openai-whisper-asr-service
spec:
  selector:
    app: openai-whisper-asr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP