apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: database

---
apiVersion: v1
kind: Service
metadata:
  name: hedgedoc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: hedgedoc
