apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: biliup-claim0
  name: biliup-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Mi
