apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: biliup
  name: biliup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: biliup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: biliup
    spec:
      containers:
        - args:
            - --password
            - $(PASSWORD)  # 使用环境变量
          image: ghcr.io/biliup/caution:latest
          name: biliup
          ports:
            - containerPort: 19159
              protocol: TCP
          volumeMounts:
            - mountPath: /opt
              name: biliup-claim0
          env:  # 添加环境变量
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: biliup-secret
                  key: password
      restartPolicy: Always
      volumes:
        - name: biliup-claim0
          persistentVolumeClaim:
            claimName: biliup-claim0
