apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: kubespider
  name: kubespider
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kubespider
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kb: "true"
        io.kompose.service: kubespider
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Asia/Shanghai
          image: cesign/kubespider:latest
          name: kubespider
          ports:
            - containerPort: 3080
              hostPort: 3080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/.config
              name: kubespider-claim0
      restartPolicy: Always
      volumes:
        - name: kubespider-claim0
          persistentVolumeClaim:
            claimName: kubespider-claim0
status: {}
