apiVersion: v1
kind: Pod
metadata:
  name: chatgpt-pod
spec:
  containers:
  - name: chatgpt-container
    labels:
      app: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    ports:
    - containerPort: 3000
    env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: chatgpt-secrets
          key: OPENAI_API_KEY
    - name: CODE
      valueFrom:
        secretKeyRef:
          name: chatgpt-secrets
          key: CODE
    - name: BASE_URL
      valueFrom:
        secretKeyRef:
          name: chatgpt-secrets
          key: BASE_URL