apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: blmysql
  name: blmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blmysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/blossom-blossomnet: "true"
        io.kompose.service: blmysql
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: MYSQL_DATABASE
              value: blossom
            - name: MYSQL_ROOT_PASSWORD
              value: jasmine888
            - name: TZ
              value: Asia/Shanghai
          image: mysql:8.0.31
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - -uroot
                - -pjasmine888
                - ping
                - -h
                - localhost
            failureThreshold: 12
            periodSeconds: 10
            timeoutSeconds: 3
          name: blossom-mysql
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: blmysql-claim0
            - mountPath: /var/log/mysql
              name: blmysql-claim1
            - mountPath: /var/lib/mysql-files
              name: blmysql-claim2
      restartPolicy: Always
      volumes:
        - name: blmysql-claim0
          persistentVolumeClaim:
            claimName: blmysql-claim0
        - name: blmysql-claim1
          persistentVolumeClaim:
            claimName: blmysql-claim1
        - name: blmysql-claim2
          persistentVolumeClaim:
            claimName: blmysql-claim2
