apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reverse-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: reverse-proxy
    spec:
      containers:
        - args:
            - caddy
            - reverse-proxy
            - --from
            - --to
            - api:8080
          image: caddy:2.3.0-alpine
          name: xbs-reverse-proxy
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: xbs-caddy-config
            - mountPath: /data
              name: xbs-caddy-data
      restartPolicy: Always
      volumes:
        - name: xbs-caddy-config
          persistentVolumeClaim:
            claimName: xbs-caddy-config
        - name: xbs-caddy-data
          persistentVolumeClaim:
            claimName: xbs-caddy-data
