apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: ${DOCKER_COMPOSE_POSTGRES_DATABASE:-etherpad}
        - name: POSTGRES_PASSWORD
          value: ${DOCKER_COMPOSE_POSTGRES_PASSWORD:-admin}
        - name: POSTGRES_USER
          value: ${DOCKER_COMPOSE_POSTGRES_USER:-admin}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: etherpad
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
