apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-var
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
