apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: podsync
  name: podsync
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: podsync
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/podsync-default: "true"
        io.kompose.service: podsync
    spec:
      containers:
        - image: ghcr.io/chjtxwd/podsync:nightly
          name: podsync
          command: ["/app/podsync", "-c", "/app/config/config.toml"]
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: podsync-claim0
            - mountPath: /app/config
              name: podsync-config
      restartPolicy: Always
      volumes:
        - name: podsync-claim0
          persistentVolumeClaim:
            claimName: podsync-claim0
        - name: podsync-config
          secret:
            secretName: podsync-config
status: {}
