apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: freshrss
  name: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: freshrss
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/freshrss-default: "true"
        io.kompose.service: freshrss
    spec:
      initContainers:
        - name: download-extension
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /config/www/freshrss/extensions && \
              curl -L -o /tmp/TranslateTitlesCN.zip https://github.com/yarin-zhang/FreshRSS-TranslateTitlesCN/releases/download/v0.3.1/TranslateTitlesCN.zip && \
              unzip /tmp/TranslateTitlesCN.zip -d /config/www/freshrss/extensions && \
              rm /tmp/TranslateTitlesCN.zip
          volumeMounts:
            - mountPath: /config
              name: freshrss-claim0
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: lscr.io/linuxserver/freshrss:latest
          name: freshrss
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: freshrss-claim0
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: freshrss-claim0
          persistentVolumeClaim:
            claimName: freshrss-claim0
