apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: nexus
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/nexus-default: "true"
        io.kompose.service: nexus
    spec:
      containers:
        - image: sonatype/nexus3
          name: nexus
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
            - containerPort: 8085
              hostPort: 8085
              protocol: TCP
          volumeMounts:
            - mountPath: /sonatype-work
              name: nexus-data
      restartPolicy: Always
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
