apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: wallabag
  name: wallabag
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: wallabag
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/wallabag-default: "true"
        io.kompose.service: wallabag
    spec:
      containers:
        - env:
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: http://localhost
            - name: SYMFONY__ENV__FROM_EMAIL
              value: chjtxwd@vip.qq.com
            - name: SYMFONY__ENV__MAILER_DSN
              value: smtp://127.0.0.1
            - name: SYMFONY__ENV__SERVER_NAME
              value: '"Your wallabag instance"'
          image: wallabag/wallabag
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl --head --fail --silent --max-time 5 http://localhost >/dev/null"
            timeoutSeconds: 600
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl --head --fail --silent --max-time 5 http://localhost >/dev/null"
            timeoutSeconds: 3600
          name: wallabag
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/wallabag/web/assets/images
              name: wallabag-claim0
      restartPolicy: Always
      volumes:
        - name: wallabag-claim0
          persistentVolumeClaim:
            claimName: wallabag-claim0
status: {}