apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: init-container
      image: busybox
      command: ["/bin/sh", "-c", "echo 'Initializing wallabag database' > /var/www/wallabag/data/db/wallabag.sqlite"]
      volumeMounts:
        - name: wallabag-data
          mountPath: /var/www/wallabag/data/db
  volumes:
    - name: wallabag-data
      persistentVolumeClaim:
        claimName: wallabag-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-pvc
      containers:
        - name: wallabag
          image: wallabag/wallabag
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://wallabag.haijin666.top"
          volumeMounts:
            - name: wallabag-data
              mountPath: /var/www/wallabag/data/db
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
