apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      nodeSelector:        
        kubernetes.io/arch: arm64 
      containers:
        - name: wallabag
          image: wallabag/wallabag
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://wallabag.haijin666.top"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10