apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wuhu/prod/argo-workflow
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
    targetRevision: HEAD
