apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wuhu/prod/csi-driver-smb/
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
