apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argo
spec:
  destination:
    namespace: navidrome
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wuhu/prod/navidrome
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
    targetRevision: HEAD
