apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wuhu/prod/prometheus
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
    targetRevision: HEAD
