apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argo
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wuhu/prod/uptime-kuma
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
    targetRevision: HEAD
