apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: picseal
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: picseal
    server: https://kubernetes.default.svc
  project: default
  source:
    path: oracle/prod/picseal
    repoURL: https://github.com/chjtxwd/homelab-k3s-gitops
    targetRevision: HEAD
